name: high_in_flutter
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quick_actions: ^1.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  google_fonts: ^3.0.1
  dio: ^4.0.6
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  just_audio: ^0.9.27
  cached_network_image: ^3.2.0
  firebase_crashlytics: ^2.8.5
  firebase_core: ^1.19.2
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.5
  marquee: ^2.2.1
  shimmer: ^2.0.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.1.0
  build_runner: ^2.2.0
  msix: ^3.6.3

msix_config:
  display_name: High in Flutter
  publisher_display_name: HighInFlutter
  identity_name: com.highinflutter
  msix_version: 0.0.0.1
  logo_path: assets/icon/logo.png
  capabilities: internetClient, location
  certificate_path: C:\drumkiller\keys\highinflutterCertificate.pfx
  certificate_password: password123



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/app_logo_example/
    - assets/images/spotify_assets/
    - assets/images/spotify_assets/mp3/
    - assets/images/singleton/
